api/urls.py
from django.urls import path, include
from . import views

app_name = "api"

urlpatterns = [
    path("sms/", views.sms, name="sms"),
    path("emails/", views.email, name="email"),
]

pages/urls.py
from django.urls import path


from . import views

app_name = "pages"


urlpatterns = [
    path("", views.home_view, name="home"),
    path("GenderGap/", views.genderGap, name="genderGap"),
    path("AboutUs/", views.aboutUs, name="aboutUs"),
]

unti_discrimination/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls", namespace="pages")),
    path("api/", include("api.urls", namespace="api")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

api/models.py
from django.db import models

# Create your models here.

api/views.py
from django.shortcuts import render
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
import vonage
from mailjet_rest import Client
import os
import requests


@api_view(['POST'])
def sms(request):
    toNumber = request.data['recipient']
    text = request.data['message']
    sms_client = vonage.Client(key="f20098bc", secret="e4RPKVZlwEJx53bE")
    sms = vonage.Sms(sms_client)
    responseData = sms.send_message(
        {
            "from": "+639565283327",
            "to": toNumber,
            "text": text,
        }
    )
    if responseData["messages"][0]["status"] == "0":
        return Response({'status': 'ok'}, status=status.HTTP_200_OK)
    else:
        return Response({'status': 'Not Acceptable'}, status=status.HTTP_406_NOT_ACCEPTABLE)


@api_view(['POST'])
def email(request):
    toEmail = request.data['to']
    toName = request.data['name']

    dueDate = request.data['date']
    bill = request.data['bill']
    reading = request.data['reading']
    totalPayed = request.data['payed']
    penalty = request.data['penalty']

    api_key = '1afdfa69d12ff3319b3b9ce17abeedbc'
    api_secret = '309be1056d38f5eb2913b6fbfe5ca47b'
    mailjet = Client(auth=(api_key, api_secret), version='v3.1')
    data = {
        'Messages': [
            {
                "From": {
                    "Email": "aiwell.talaironwater@gmail.com",
                    "Name": "Aiwell"
                },
                "To": [
                    {
                        "Email": toEmail,
                        "Name": toName
                    }
                ],
                "Subject": "Payment Confirmation",
                "HTMLPart": f"<h3>Dear {toName}</h3> <h5>Payment Confirmation!!!</h5><br><span>Due Date: {dueDate}</span><br><span>Bill: {bill}</span><br><span>Reading: {reading}m<sup>3</sup></span><br><span>Penalty: {penalty}</span><br><span>Total Payed: {totalPayed}</span><br><h3>Thank You!!!</h3>",
                "CustomID": "AppGettingStartedTest"
            }
        ]
    }
    result = mailjet.send.create(data=data)
    return Response({'status': 'ok'}, status=status.HTTP_200_OK)

pages/views.py
from django.shortcuts import render

# Create your views here.


def home_view(request):
    return render(request, "home.html", {})

def genderGap(request):
    return render(request, "gendergap.html", {})

def aboutUs(request):
    return render(request, "aboutus.html", {})

pages/templates/aboutus.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}
<title>About Us</title>
{% endblock %}
           
{% block content %}
    <div>
        <div>
            <img style="width: 100%;"  class="img-fluid" src="{% static 'images/oroquieta.jpg' %}" alt="">
        </div>
        <div class="container-fluid" style="padding: 20px;">
            <p style="font-size: 20px; text-align: justify;">
                Oroquieta was called before as Layawan. 
                The now city was then a barrio in the province of Misamis since 1861 
                to 1879. The early settlers were Boholano peddlers. 
                Since much of the animals can be found along the river, 
                the named the place Layawan, which means place of many stray animals.
                <br><br>
                After some years, Misamis was divided into two provinces, 
                Misamis Occidental and Misamis Oriental. In 1880, Layawan converted 
                into a town and the name of the place was changed to Oroquieta. 
                Some folks say that the the place was named after the famous 
                barrio in Spain where Father Toas Tomas Casado, the first 
                parish priest and General Domingo Mariones y Murillo, a hero 
                in the battle of Oroquieta, were born.
                <br><br>
                Many years had passed, Oroquieta progressed by leaps and bounds 
                until finally it became the capital town (cabecera) on January 6, 
                1930. As capital town, people of various neighboring provinces came
                 and inhabited in the place where they earn their living through 
                 fishing, farming, merchandising and other forms of businesses. 
                 Soon afterwards its income increased simultaneously with increase 
                 in population.
            </p>
        </div>
        <div class="container" id="ContactUs" style="height: 150px;">

        </div>
        <div class="container text-center">
            <h1>Contact Us</h1>
            <p style="font-size: 20px;">
                If you have some issues about gender equality, 
                please don't hesitate to email us
                @ oro.genderdevelopment@gmail.com
                or call/text us at 09232232326<br>
            </p><br>
            <p style="font-size: 20px;">
                You can also send a direct message in our site
                by just filling the fields below
            </p>
            <form class="col-md-6 col-sm-12 offset-md-3 border border-1" style="padding: 20px;" action="#">
                <div class="mb-3 row">
                    <label for="staticEmail" class="col-sm-2 col-form-label">Email</label>
                    <div class="col-sm-10">
                      <input type="email" class="form-control" required id="staticEmail" placeholder="email@example.com">
                    </div>
                  </div>
                  <div class="mb-3 row">
                    <label for="" class="col-sm-2 col-form-label">Message</label>
                    <div class="col-sm-10">
                      <input type="text" required class="form-control" id="">
                    </div>
                  </div>
                  <div class="mb-3 row">
                    <label for="" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10">
                        <input type="submit"  class="form-control btn btn-secondary" value="Submit" id="">
                      </div>
                    
                  </div>
                  
            </form><br><br>
        </div>
    </div>
{% endblock %}

pages/templates/gendergap.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}
<title>Gender Gap</title>
{% endblock %}
           
{% block content %}
    <div>
        <div class="container-fluid">
            <div class="row">
                    <div class="col-md-6 col-sm-12" style="padding: 1px;">
                        <img  class="img-fluid" src="{% static 'images/gender.png' %}" alt="">
                    </div>
                    <div class="col-md-6 col-sm-12 text-center" style="padding-right: 20px;"><br>           
                        <p style="font-size: 20px; text-align: justify;">
                            The Philippines remains the top country in Asia in terms of 
                            closing the gender gap, according to the Global Gender Gap 
                            Report 2020 of the World Economic Forum. <br><br>

                            The report shows that the Philippines has closed 78% of its 
                            overall gender gap, garnering a score of 0.781 (down by 1.8 
                            percentage points from .799 in 2019). With this, it ranked 
                            16th out of 153 countries with the narrowest gap between men 
                            and women, dropping by 8 notches from its place last year.
                            <br><br>
                            Notably, it remains as the sole Asian country that made it to 
                            the top twenty tier; followed by Lao People’s Democratic 
                            Republic which ranked 43rd.
                            <br><br>
                            The Global Gender Gap Report 2020 measured countries on 
                            their progress towards gender parity in four dimensions: 
                            economic participation and opportunity, educational attainment,
                             health and survival, and political empowerment.
                        </p> 
                    </div>
            </div>
            
        </div>
    </div>
{% endblock %}

pages/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-2.2.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">
    {% block title %}
   
    {% endblock %}
    
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="position:fixed; width: 100%;">
        <div class="container-fluid">
            <div class="container" style="max-width: 950px;">
                <h2>
                    Gender and Development of LGU Oroquieta
                </h2>
            </div>
            
            <button class="navbar-toggler" id="menuToggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a style="font-size: 20px;" class="nav-link active" aria-current="page" href="{% url 'pages:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a style="font-size: 20px;" class="nav-link" href="{% url 'pages:home' %}#LGBTQIA+">LGBTQIA+</a>
                    </li>
                    <li class="nav-item">
                        <a style="font-size: 20px;" class="nav-link" href="{% url 'pages:genderGap' %}">
                        Gender Gap
                        </a>
                    </li>
                    <li class="nav-item">
                        <a style="font-size: 20px;" href="{% url 'pages:aboutUs' %}" class="nav-link">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a style="font-size: 20px;" href="{% url 'pages:aboutUs' %}#ContactUs"" class="nav-link">Contact Us</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container" id="separator">

    </div>
    {% block content %}

    {% endblock %}
    <div class="bg-secondary" style="text-align:center; height: 150px; padding: 30px;">
            <span>Copyright &copy; EliteBuilders 2022</span>
    </div>
</body>
<script>
  var height = document.querySelector('.navbar').clientHeight;
  document.querySelector('#separator').style.height = height+'px';
  $(document).ready(function(){
      $('.nav-link').click(function(){
          $('#navbarSupportedContent').toggle();
      })
      $('#menuToggler').click(function(){
          $('#navbarSupportedContent').toggle();
      })
  })

//   var element = document.querySelectorAll('.nav-link');
//   document.querySelector('.nav-link').click=function(){
//       alert('yes')
//   }
</script>
</html>